# Generated by Django 5.2.1 on 2025-06-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_games_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
