# Generated by Django 5.2.1 on 2025-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_games_app', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leaderboards',
            fields=[
                ('leaderboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('ranking', models.IntegerField()),
                ('score', models.IntegerField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
                'db_table': 'leaderboards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
                'managed': False,
            },
        ),
    ]
