# Generated by Django 5.2.1 on 2025-07-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_games_app', '0006_userprofiles_volume_alter_userprofiles_is_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='volume',
        ),
    ]
