# Generated by Django 5.2.1 on 2025-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_games_app', '0007_remove_userprofiles_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='userprofiles',
            table='user_profiles',
        ),
    ]
