# Generated by Django 5.2.1 on 2025-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_games_app', '0004_profile'),
        ('cv_games_app', '0008_alter_userprofiles_options_and_more'),
    ]

    operations = [
    ]
